version: '3.6'
services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: progmo

  dbadmin:
    image: adminer
    container_name: dbadmin
    restart: always
    ports:
      - 8080:8080

  progmo:
    build: ./src
    container_name: progmo